- name: Preparando /etc/hosts
  gather_facts: True
  hosts: nuevos
#  vars_prompt:
#     - name: "name"
#       prompt: "Ingresar nombre de host"
#       private: yes
  tasks: 
    - lineinfile:
        path: /etc/hosts
        line: '127.0.0.1 localhost'
        state: present
#       regexp: '^127\.0\.0\.1'
        backup: yes
    - name: Prueba de variables
         debug:
            msg: "System {{ nombre_equipo }}"
