---
- hosts: tower
  remote_user: root
#  become: true
  vars:
    - tower_path: /tmp/ansible-tower-setup-bundle-3.1.4-1.el7
    - tower_admin_pass: redhat
    - rhn_username: Tu-user
    - rhn_pass: Tu-password
    - hostname_full: Host-name-full
  tasks:
    - name: Registrando Sistema en Portal de Red Hat.
      redhat_subscription:
          state: present
          username: " {{ rhn_username }} " 
          password: "{{ rhn_pass }}"
          consumer_name: "{{ hostname_full }}"
          autosubscribe: true
          force_register: yes

    - name: Habilitando canales necesarios.
      shell: |
        subscription-manager repos --disable=*
        subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-extras-rpms --enable rhel-7-server-optional-rpms

    - name: Actualizando Sistema Operativo
      yum:
        name: '*'
        state: latest
        
    - name: "Limpiando metadata de los repositorios."
      command: "yum clean all"

    - name: Restart server
      shell: reboot

    - name: Wait for server to restart
      local_action:
        module: wait_for
          host={{ ansible_default_ipv4.address }}
          port=22
          delay=3
          timeout=60
          state=started

    - name: Descargando Ansible Tower.
      get_url:
        url: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
        dest: /tmp 

    - name: Extrayendo Ansible Tower.
      unarchive:
        src: /tmp/ansible-tower-setup-bundle-latest.el7.tar.gz 
        dest: /tmp
        remote_src: yes

    - name: Configurando Password Admin.
      lineinfile: 
        dest: "{{ tower_path }}/inventory"
        regexp: admin_password
        line: "admin_password='{{ tower_admin_pass }}'"

    - name: Configurando Password Rabbitmq.
      lineinfile:
        dest: "{{ tower_path }}/inventory"
        regexp: rabbitmq_password
        line: "rabbitmq_password='{{ tower_admin_pass }}'"

    - name: Configurando Password PG.
      lineinfile:
        dest: "{{ tower_path }}/inventory"
        regexp: pg_password
        line: "pg_password='{{ tower_admin_pass }}'"

    - name: Instalando Tower.
      shell: | 
        ./setup.sh
      args:
        chdir: "{{ tower_path }}"
