---
- name: Registro de Sistema operativo vía subscription manager.
  gather_facts: True
  hosts: localhost
  ansible_become: True
  tasks:
     - file:
          path: /etc/foo.conf
          state: touch
          mode: "u=rw,g=r,o=r"
       ignore_errors: True
#######################################################
#                                                     #
# Creando Servidor IPA  GCP                           #
#                                                     #
#######################################################
- name: Instalacion de Servidor IPA
  include: tareas/servidor-base.yaml
  ignore_errors: True


######################################################
#                                                    #
# Instalacion y configuración Server IPA             #
#                                                    #
######################################################

#- name: Instalacion de Servidor IPA
#  include: ipa-server/deploy-ipa-server-2.yaml
#  ignore_errors: True
######################################################
#                                                    #
# Enviando Notificaciones a los usuarios             #
#                                                    #
######################################################
