---
- name: Registro de Sistema operativo vía subscription manager.
  gather_facts: True
  hosts: 35.185.58.17
  tasks:
     - file: 
          path: /{{ mapm }}
          owner: foo
          group: foo
          mode: 0644
       ignore_errors: True
#######################################################
#                                                     #
# Creando Servidor IPA  GCP                           #
#                                                     #
#######################################################
- name: Instalacion de Servidor IPA
  include: tareas/servidor-base.yaml
  ignore_errors: True


######################################################
#                                                    #
# Instalacion y configuración Server IPA             #
#                                                    #
######################################################

#- name: Instalacion de Servidor IPA
#  include: ipa-server/deploy-ipa-server-2.yaml
#  ignore_errors: True
######################################################
#                                                    #
# Enviando Notificaciones a los usuarios             #
#                                                    #
######################################################
