---
- name: Registro de Sistema operativo vía subscription manager.
  gather_facts: True
  hosts: nuevos
  tasks:
     - name: Print mosh version
       debug: msg="address={{ ansible_default_ipv4.address }}"
     - template:
         src: templates/dump_variables
         dest: /tmp/ansible_variables
     - fetch:
         src: /tmp/ansible_variables
         dest: "{{inventory_hostname}}_ansible_variables"
#######################################################
#                                                     #
# Creando Servidor IPA  GCP                           #
#                                                     #
#######################################################
- name: Instalacion de Servidor IPA
  include: tareas/servidor-base.yaml
  ignore_errors: True


######################################################
#                                                    #
# Instalacion y configuración Server IPA             #
#                                                    #
######################################################

#- name: Instalacion de Servidor IPA
#  include: ipa-server/deploy-ipa-server-2.yaml
#  ignore_errors: True
######################################################
#                                                    #
# Enviando Notificaciones a los usuarios             #
#                                                    #
######################################################
