---
- name: PLAYBOOK DE TAREAS POS-INSTALACIÓN RHEL 7
  gather_facts: True
  hosts: nuevos
  tasks:

# si necesitamos variables predefinidas y no habilitamos 
# "gather_facts: False" podemos hacer un filtrado solo -
# de la información que necesitamos con el siguiente ---
# módulo.
#
#    - setup:
#          filter: name*
#          gather_subset: network,virtual
#          filter=ansible_eth[0-2]
#          filter=ansible_*_mb

#######################################################
# Tareas de registro a RHN:                           #
#     Usuario.                                        #
#     Password.                                       #
#     Asignación de pool en suscripción.              #
#     Deshabilitación de repositorios innecesarios.   #
#     Asignación de repositorios base.                #
#######################################################
- name: Registro de equipo vía Subscription Manager.
  include: task/post-install.yaml
  ignore_errors: True


######################################################
#                                                    #
# Instalacion y configuración Server IPA             #
#                                                    #
######################################################

#- name: Instalacion de Servidor IPA
#  include: ipa-server/deploy-ipa-server-2.yaml
#  ignore_errors: True
######################################################
#                                                    #
# Enviando Notificaciones a los usuarios             #
#                                                    #
######################################################
